functionsDirectory = "C:\\Users\\fives\\.gemini\\antigravity\\scratch\\edexcelgcsehistoryusa.netlify.app\\netlify\\functions"
functionsDirectoryOrigin = "default"
plugins = []
headers = []
redirects = []

[build]
publish = "C:\\Users\\fives\\.gemini\\antigravity\\scratch\\edexcelgcsehistoryusa.netlify.app\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "C:\\Users\\fives\\.gemini\\antigravity\\scratch\\edexcelgcsehistoryusa.netlify.app\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]