import fs from 'fs';
import { EXAM_SKILLS_DATA, PAST_PAPERS_DATA } from '../questions.js';

const NEW_MODELS = {
  q3_1: `Source B is highly useful for demonstrating the legal litigation strategy of the NAACP. The content highlights how their legal campaigns are “finally bearing fruit” by targeting segregated institutions, allowing them to successfully challenge segregation in courts. This is supported by my contextual knowledge that [[the NAACP won the Brown v. Board of Education case in 1954, declaring segregated schools unconstitutional, and had previously won Sweatt v. Painter in 1950]]. The provenance makes the source more useful because it is an internal, private report written by lead lawyer Thurgood Marshall in 1953. Since it was not intended for public propaganda, it represents a highly reliable, realistic assessment of NAACP strategy and confidence just before their major legal victories.

Source C is highly useful for showing the direct action methods of CORE and the severe grassroots opposition they faced. The activist describes staging a “peaceful sit-in at the downtown lunch counter” but being met with a white mob that “spat on, kicked, and dragged” them while police stood by. This is supported by my knowledge that [[CORE pioneered non-violent direct action, including lunch counter sit-ins, in Northern and Midwestern cities in the 1940s and 1950s, though they faced intense local resistance]]. The provenance increases its usefulness because it is a first-hand account by a CORE activist published in a contemporary newsletter in 1952. While the newsletter was designed to motivate members, which might emphasize the drama, it is extremely useful for revealing the immediate physical dangers, emotional frustrations, and reliance on alternative media to publicize their struggle.`,

  q3_2: `Source B is highly useful for showing the persistent racial inequalities and lack of economic progress by the late 1960s. The report warns that the nation is “moving toward two societies, one black, one white—separate and unequal” due to the maintaining of segregated ghettos. This is supported by my contextual knowledge that [[despite civil rights legislation, deep-seated economic inequality and police brutality led to major race riots in Watts (1965), Newark, and Detroit (1967), showing the limits of legal progress]]. The provenance strengthens its usefulness because it is an official government-commissioned report from the Kerner Commission in 1968. Since it was compiled by moderate white politicians who concluded that white institutional racism was responsible, it provides a highly reliable, objective official admission of the limits of legal progress.

Source C is highly useful for demonstrating the significant political and social achievements of the civil rights movement by the mid-1970s. The politician asserts that the changes are “monumental” because the “Whites Only” signs are gone and Black citizens are electing “black mayors in major American cities”. This is supported by my knowledge that [[the Voting Rights Act of 1965 led to a dramatic increase in Black political representation and the election of Black mayors, while Nixon's affirmative action policies opened corporate hiring]]. The provenance increases its usefulness because it is a contemporary interview from 1974 with a politician active in the movement. While he may have a bias toward highlighting political success to justify his career, it is highly useful for showing the perspective of Black leaders who successfully transitioned from street activism to institutional political power.`,

  p_2019_q3: `Source B is highly useful for showing the monumental federal legislative achievements of the movement and the cooperation between the president and civil rights leaders. The photograph shows “President Johnson shaking hands with Martin Luther King Jr., presenting him with a pen” at the signing ceremony. This is supported by my knowledge that [[the Civil Rights Act of 1964 was a major legislative victory that outlawed segregation in public accommodations and employment, representing a massive victory for the NAACP and SCLC campaigns]]. The provenance strengthens the source's usefulness because it was published on the front page of several newspapers in July 1964. While it was a carefully managed media event designed to project national unity and federal power, it is extremely useful for demonstrating how the federal government sought to publicly validate and celebrate its alliance with the civil rights movement.

Source C is highly useful for showing the violent opposition activists faced on the ground and how it pressured the government to enact further reform. John Lewis describes being attacked on a bridge by state police who “released tear gas” and hit him with a truncheon, which led to Johnson introducing the “Voting Rights Act”. This is supported by my knowledge that [[the Selma to Montgomery marches in March 1965, known as Bloody Sunday, were met with state trooper violence, which shocked the public and forced President Johnson to introduce the Voting Rights Act of 1965]]. The provenance, a 2009 radio interview with activist John Lewis, makes it more useful because it is a direct first-hand recollection of a key leader of the march. However, because it was recorded over forty years later, some specific details might be subject to retrospective framing, yet it remains highly useful for understanding the emotional and physical sacrifices of the protestors.`,

  p_2020_q3: `Source B is highly useful for demonstrating the military failure of US bombing strategies to disrupt North Vietnamese supply lines. The reports state that despite air force bombing, “the communists have actually been able to increase their movement of soldiers and supplies” and that bombing had “not weakened the determination” of the enemy. This is supported by my knowledge that [[Operation Rolling Thunder, launched in 1965, failed to stop infiltration along the Ho Chi Minh Trail and instead strengthened North Vietnamese resolve to resist US aggression]]. The provenance makes this source exceptionally useful because it consists of secret internal military intelligence reports from 1966, kept classified until 1993. Because these reports were confidential and not meant to mislead the US public, they represent an honest, objective contemporary assessment of the limits of US air power.

Source C is highly useful for showing the breakdown of discipline, morale, and cohesion within the US military as a reason for defeat. The soldier recalls that “morale got worse over time”, soldiers were “high on drugs all the time”, and that men killed an incompetent officer by “throwing a grenade into his hut”. This is supported by my knowledge that [[by the early 1970s, the US military faced a severe crisis of morale, with widespread drug abuse, high desertion rates, and over 800 recorded incidents of fragging, reflecting deep frustration with the draft and the war]]. The provenance, a 1981 television interview, makes it useful for providing a candid, retrospectively honest account of the internal collapse of combat units. However, because it was recorded ten years after his service and for a television broadcast, the soldier may have highlighted sensational aspects, though it remains highly useful for illustrating the psychological toll and disintegration of military discipline.`,

  p_2022_q3: `Source B is highly useful for understanding the militant methods and self-defense posture of the Black Panthers. Seale describes conducting “armed patrols” and carrying guns to “observe these police in the community, and to make sure there's not going to be any more police brutality”. This is supported by my knowledge that [[the Black Panthers were founded in Oakland in 1966 by Bobby Seale and Huey Newton, carrying loaded weapons to patrol neighborhoods and monitor police arrests under California open-carry laws]]. The provenance makes it useful because it is a direct account by the co-founder of the party. However, because it was recorded in 1988, long after the movement had declined, Seale may have been trying to retrospectively emphasize their disciplined, defensive role rather than their revolutionary rhetoric, but it is highly useful for illustrating the initial confrontational tactics used to challenge police authority.

Source C is highly useful for showing the community-oriented social programs that the Black Panthers used to build support. The article highlights their “Free Breakfast for School Children” scheme because their “love for the people makes us realise that we must provide free breakfasts right across the country”. This is supported by my knowledge that [[the Black Panthers ran over 40 community programs, serving breakfasts to thousands of children daily, which built strong local loyalty and contrasted sharply with their media image as violent extremists]]. The provenance increases its usefulness because it comes from their official newspaper published in 1969. While the newspaper was a propaganda tool aimed at recruiting and presenting a positive image, it is extremely useful for showing how they used social welfare to mobilize urban communities and construct a positive national brand.`,

  p_2023_q3: `Source B is highly useful for showing the positive psychological and educational impact of Freedom Summer on local Black youth. Gandy recalls that the summer was a “turning point” and that the “white volunteers who came to us started something great” that inspired locals to stage their own boycotts. This is supported by my knowledge that [[the Freedom Summer project in 1964 set up over 40 Freedom Schools in Mississippi, teaching academic skills and civil rights history to over 3,000 Black children to foster local leadership]]. The provenance increases its usefulness because it provides the perspective of a local Black child who actually attended a Freedom School. Although recorded in 2015 as a distant recollection, which might romanticize the experience, it is highly useful for showing the long-term impact of the campaign in inspiring lifetime activism in the community.

Source C is highly useful for demonstrating the extreme violence, intimidation, and legal obstruction used to stop civil rights work. The log records that a “church used as a Freedom Summer School” was burned, homes were bombed, and a “missing car found burned; no sign of three civil rights workers”. This is supported by my knowledge that [[the Freedom Summer faced severe white backlash, including the murder of James Chaney, Andrew Goodman, and Michael Schwerner in Philadelphia, Mississippi, and the firebombing of numerous Black churches]]. The provenance strengthens the source's usefulness because it is a contemporary log of incidents recorded directly by organizers in June 1964. Since it was kept to coordinate security and updates, it is a highly reliable, detailed record of the daily physical terror and systemic police harassment faced by volunteers.`,

  p_2024_q3: `Source B is highly useful for showing King's ability to mobilize massive, diverse public support and his role as a symbolic national leader. The photograph depicts King “waving to a massive, densely packed crowd of demonstrators” along the reflecting pool in Washington D.C. This is supported by my knowledge that [[the March on Washington in August 1963 attracted over 250,000 participants, where King delivered his famous 'I Have a Dream' speech, putting pressure on Congress to pass civil rights legislation]]. The provenance makes it useful because it is a contemporary photograph of one of the largest political rallies in US history. While it captures a polished, celebratory moment that downplays internal tensions within the movement, it is extremely useful for demonstrating the visual scale of King's popular support and his status as a unifying national figure.

Source C is highly useful for showing the limits of King's achievements when campaigning in the North and the rise of internal divisions. Lucas states that King “failed to get improved living conditions for Black Americans in Chicago” and that his departure revealed a “wider split between the Black activists and White activists”. This is supported by my knowledge that [[the Chicago Freedom Movement in 1966 struggled against Mayor Daley's political machine and failed to secure lasting housing reforms, which accelerated the rise of the Black Power movement and the rejection of white allies]]. The provenance increases its usefulness because it is an account by Bob Lucas, a Black civil rights leader who worked directly with King in Chicago. While recorded retrospectively in a television documentary, his position as an insider makes it highly useful for explaining the shift from integrationist tactics to racial self-reliance within the activist ranks.`,

  p_2025_q3: `Source B is highly useful for showing the early stage of US military escalation under President Kennedy. The document lists actions showing that “President Kennedy has authorised government officials” to provide Diem with “increased air support”, helicopters, and “individual administrators and advisers”. This is supported by my knowledge that [[President Kennedy escalated US involvement by sending Green Berets and increasing military advisers from 800 to over 16,000 by 1963 to prop up the Diem regime]]. The provenance makes the source exceptionally useful because it was a top-secret government document from 1961. Since it was not meant for public consumption, it reveals the secret, early steps of escalation before the public introduction of combat troops, free from public relations spin.

Source C is highly useful for demonstrating the massive escalation of US combat involvement under President Johnson. Johnson announces that he has “ordered an additional Air Division and other forces to go to Vietnam” to raise strength to “125,000 men almost immediately” and will increase “the draft system”. This is supported by my knowledge that [[following the Gulf of Tonkin Resolution in 1964, Johnson rapidly escalated US involvement, committing the first ground troops in March 1965 and raising the total force to over 180,000 by the end of 1965 through the draft]]. The provenance makes it useful because it is a direct public speech by the President in July 1965. Although it contains political justifications to present the escalation as a defensive necessity to resist aggression and rally the American public, it is highly useful for documenting the official, overt transition to full-scale US combat operations in Vietnam.`,

  mock_exam_1: `Source B is highly useful for showing the hostile reaction of northern white working-class residents to King's campaign. The resident complains that King “stirred up trouble where there was none” and that the marches “just made people angry” and caused riots. This is supported by my knowledge that [[King's Chicago campaign in 1966 targeted housing segregation, which faced fierce opposition from white working-class neighborhoods who feared falling property values and integration]]. The provenance makes this source useful because it is an interview published in a local newspaper shortly after the marches in 1966. While it reflects a narrow, defensive viewpoint that downplays systemic northern racism, it is highly useful for showing the immediate resentment and racial defensiveness of Chicago's white residents who refused to see their city as segregated.

Source C is highly useful for demonstrating the extreme violence that civil rights protestors faced in the North. The activist describes marching through Cicero and being met with “bricks and bottles from a white mob”, noting that the hatred was “worse than anything he had faced in Mississippi”. This is supported by my knowledge that [[during the SCLC marches in Chicago suburbs like Cicero and Marquette Park, protestors were met by thousands of violent white residents throwing bricks, showing that Northern housing segregation was maintained with the same brutality as Southern Jim Crow]]. The provenance strengthens the source's usefulness because it is a first-hand account by an SCLC activist who participated in the march. While he has an interest in emphasizing the violence to expose Northern racism to the world, it is highly useful for capturing the physical danger and disillusionment of the campaigners.`,

  mock_exam_2: `Source B is highly useful for showing the shock and anger felt by students at Kent State and their view of government repression. The student describes holding a “peaceful rally against the President's illegal invasion of Cambodia” when the National Guard fired, showing that “the government was willing to murder its own youth”. This is supported by my knowledge that [[the Kent State shooting in May 1970 occurred during protests against Nixon's expansion of the war into Cambodia, triggering a nationwide student strike of over 4 million students]]. The provenance makes it useful because it is a contemporary, eyewitness account published in a student magazine in May 1970. While it is highly emotional and presents the protest as entirely peaceful, it is highly useful for capturing the immediate sense of betrayal and the radicalization of the anti-war movement.

Source C is highly useful for understanding the Nixon administration's justification for the shootings and their political strategy. Nixon argues that “tragedy is inevitable” when students resort to throwing rocks and burning buildings, calling them “violent, anti-American radicals”. This is supported by my knowledge that [[Nixon appealed directly to the 'Silent Majority' of middle-class Americans who were growing increasingly tired of student protests, riots, and counter-culture, using law-and-order rhetoric to isolate the protestors]]. The provenance makes the source useful because it is an official speech by President Nixon in May 1970. Although it is a politically motivated speech designed to deflect blame from the National Guard and consolidate his conservative base, it is highly useful for showing how the government sought to frame the Kent State tragedy to maintain public support for its foreign policy.`,

  mock_exam_3: `Source B is highly useful for understanding how the Montgomery Bus Boycott empowered the Black community and validated non-violent direct action. The activist states that the boycott showed the “power of our community” by refusing to be intimidated for 381 days, proving that “non-violent direct action could break the back of segregation”. This is supported by my knowledge that [[the Montgomery Bus Boycott of 1955-56 successfully challenged segregation after Rosa Parks' arrest, leading to the Supreme Court ruling Browder v. Gayle that declared bus segregation unconstitutional]]. The provenance makes it useful because it is a contemporary interview with an activist in 1956. While it reflects the natural optimism and pride of a participant celebrating a major victory, it is highly useful for capturing the newfound confidence and tactical resolve that the boycott instilled in civil rights campaigners.

Source C is highly useful for understanding the resentment and resistance of white segregationists to the boycott's success. The editorial asserts that the boycott achieved nothing but “racial bitterness” and that Black maids still face “low wages and hostility from white citizens who resent being forced to mix”. This is supported by my knowledge that [[despite the legal victory on the buses, white backlash in Montgomery was severe, and Black domestic workers continued to suffer from economic inequality and white violence]]. The provenance increases its usefulness because it is an editorial in a local Montgomery newspaper published in December 1956. Although it has a clear segregationist bias designed to minimize the civil rights victory, it is highly useful for demonstrating that legal desegregation did not change deep-seated racial prejudice and instead provoked a hostile white backlash.`,

  mock_exam_4: `Source B is highly useful for showing the extreme hostility and physical terror experienced by the Black students trying to desegregate Central High School. Elizabeth Eckford recalls that guards “raised his bayonet” to block her and the crowd screamed “Lynch her! Lynch her!” as she walked alone. This is supported by my knowledge that [[in September 1957, Arkansas Governor Orval Faubus deployed the state National Guard to block the Little Rock Nine from entering Central High School, leaving Elizabeth Eckford vulnerable to the mob]]. The provenance is useful because it is a direct first-hand account by one of the Little Rock Nine. While it is a deeply emotional recollection, it is exceptionally useful for capturing the psychological trauma of the students and the failure of local authorities to protect them.

Source C is highly useful for demonstrating the federal government's intervention to enforce desegregation and maintain federal law. Eisenhower declares that “Mob rule in Little Rock cannot be allowed to override the decisions of our courts” and that he has sent the “101st Airborne Division” to guarantee safety. This is supported by my knowledge that [[Eisenhower was forced to intervene on 24 September 1957 to enforce federal court orders and protect the students, marking a major clash between state and federal authority]]. The provenance of a presidential radio address in September 1957 increases its usefulness. While Eisenhower was primarily motivated by the need to maintain federal law and protect the nation's international image during the Cold War rather than a personal passion for civil rights, it is highly useful for showing the official federal commitment to uphold the Supreme Court's Brown decision.`,

  mock_exam_5: `Source B is highly useful for showing how US military tactics alienated the civilian population in South Vietnam. The report states that heavy reliance on “search-and-destroy operations and chemical defoliants has created hundreds of thousands of refugees” and is driving peasants “directly into the arms of the enemy”. This is supported by my knowledge that [[tactics like search-and-destroy and the chemical spraying of Agent Orange under Operation Ranch Hand alienated the rural population, making it impossible to win the hearts and minds campaign]]. The provenance strengthens its usefulness because it is an official report by a US Senate Subcommittee in 1968. Since it is a self-critical government investigation, it provides a highly reliable, objective contemporary record of the counterproductive nature of US military operations.

Source C is highly useful for understanding the Vietcong perspective on US military actions and their effect on peasant recruitment. The veteran recalls that because US troops “did not know who the enemy was”, they treated everyone as Vietcong and “burned our huts and killed our livestock. This made even the quietest peasants want to fight”. This is supported by my knowledge that [[the Vietcong guerrilla strategy relied on hiding among civilians, which led frustrated US soldiers to treat all villagers as hostile, driving many peasants to support the communists]]. The provenance of a 1985 interview with a Vietcong veteran makes it useful for providing an insider's recollection of the conflict. While it may contain retrospective communist propaganda, it is highly useful for explaining how US high-firepower tactics actively fueled the insurgency.`,

  mock_exam_6: `Source B is highly useful for showing the severe military weaknesses of Vietnamization on the ground. The adviser reports that the South Vietnamese Army is “heavily dependent on US air support” and “panicked and suffered heavy casualties when they faced North Vietnamese tanks”, warning that a quick US withdrawal will lead to collapse. This is supported by my knowledge that [[in 1971, the ARVN launched Operation Lam Son 719 into Laos to cut the Ho Chi Minh Trail, which ended in a disastrous retreat that exposed the failure of Vietnamization]]. The provenance increases its usefulness because it is a confidential military report from an adviser in Saigon to the Department of Defense in 1971. Since it was an internal, realistic assessment not intended for public relations, it provides a highly reliable, realistic view of the military shortcomings of the ARVN.

Source C is highly useful for understanding the Nixon administration's public justification for withdrawing from the war and their framing of Vietnamization. Nixon announces that they have achieved an “agreement to end the war and bring peace with honor” and that Vietnamization has “trained and equipped a strong South Vietnamese army capable of defending their own independence”. This is supported by my knowledge that [[the Paris Peace Accords of January 1973 allowed the US to withdraw its troops, but left North Vietnamese forces in the South, which ultimately led to the fall of Saigon in 1975]]. The provenance of a presidential speech in January 1973 makes the source useful. Although it was a public relations speech designed to paint a face-saving exit as a success, it is highly useful for showing how the US government sought to justify the end of US combat involvement to the American public.`,

  mock_exam_7: `Source B is highly useful for showing the psychological strain and tactical difficulties faced by US ground forces in Vietnam. The soldier writes about patrolling in circles through a swamp where they “cannot see the enemy, but we know they are there” and are losing men to mines, noting that they are “fighting a shadow, and we are losing our minds”. This is supported by my knowledge that [[the Vietcong used guerrilla warfare, tunnels, and booby traps in the Mekong Delta, which neutralised US conventional firepower and caused severe psychological stress for soldiers]]. The provenance, a personal diary entry from 1967, makes the source extremely useful. Because it was written privately for himself and not for military censors or the public, it represents a highly reliable, authentic record of the daily physical and psychological toll of guerrilla warfare.

Source C is highly useful for understanding the military strategy and resilience of the communist forces. The commander explains that they “used the jungle and our tunnels to neutralise their air power” and aimed to “keep fighting until the American public grew tired of the war”. This is supported by my knowledge that [[the communists waged a war of attrition, utilizing the Cu Chi tunnels and jungle cover to survive US bombing, counting on growing anti-war sentiment in the US to force a withdrawal]]. The provenance of a post-war interview with a North Vietnamese commander in 1982 makes it useful because it offers an official retrospective explanation of their victory. While he has a natural interest in emphasizing their ideological determination and heroic sacrifice, it is highly useful for showing the strategic patience that allowed them to defeat a technologically superior superpower.`
};

let fileContent = fs.readFileSync('questions.js', 'utf8');
let replacedCount = 0;

// 1. Replace the 15 model answers in EXAM_SKILLS_DATA.q3
for (const key in EXAM_SKILLS_DATA.q3) {
  const oldModel = EXAM_SKILLS_DATA.q3[key].modela;
  const newModel = NEW_MODELS[key];
  if (!newModel) {
    console.error(`No new model answer found for key: ${key}`);
    continue;
  }
  
  const oldSerialized = JSON.stringify(oldModel);
  const newSerialized = JSON.stringify(newModel);
  
  if (fileContent.includes(oldSerialized)) {
    // We want to replace all occurrences of this exact old serialized string in the file
    // Note that mock_exam_1 and mock_exam_2 occurrences will also get replaced this way!
    const occurrences = fileContent.split(oldSerialized).length - 1;
    fileContent = fileContent.split(oldSerialized).join(newSerialized);
    replacedCount += occurrences;
    console.log(`Replaced key: ${key} (${occurrences} occurrences in file)`);
  } else {
    console.warn(`Could not find old serialized model answer for key: ${key}`);
  }
}

// 2. Replace the inline model in mock_exam_3 in PAST_PAPERS_DATA
const mock3 = PAST_PAPERS_DATA.find(p => p.id === 'mock_exam_3');
if (mock3 && mock3.q3a && mock3.q3a.model) {
  const oldModel3 = mock3.q3a.model;
  const newModel3 = NEW_MODELS.mock_exam_3;
  const oldSerialized3 = JSON.stringify(oldModel3);
  const newSerialized3 = JSON.stringify(newModel3);
  
  if (fileContent.includes(oldSerialized3)) {
    const occurrences = fileContent.split(oldSerialized3).length - 1;
    fileContent = fileContent.split(oldSerialized3).join(newSerialized3);
    replacedCount += occurrences;
    console.log(`Replaced mock_exam_3 inline model (${occurrences} occurrences)`);
  } else {
    console.warn(`Could not find old serialized mock_exam_3 inline model`);
  }
}

// Write the updated content back to questions.js
fs.writeFileSync('questions.js', fileContent, 'utf8');
console.log(`Done! Total replacements made in file: ${replacedCount}`);
