import fs from 'fs';

// Helper to escape double quotes and format text for JavaScript single-line strings in JSON
function escapeForJSON(str) {
  return JSON.stringify(str).slice(1, -1);
}

// Helper to replace the modelAnswer inside lessons_data.js
function replaceModelAnswer(content, subtopicId, newAnswer) {
  const subtopicIdx = content.indexOf(`"${subtopicId}":`);
  if (subtopicIdx === -1) throw new Error(`Subtopic ${subtopicId} not found`);

  const huIdx = content.indexOf('"howUsefulAnalyser":', subtopicIdx);
  if (huIdx === -1) throw new Error(`howUsefulAnalyser not found for ${subtopicId}`);

  const maKey = '"modelAnswer": "';
  const maIdx = content.indexOf(maKey, huIdx);
  if (maIdx === -1) throw new Error(`modelAnswer key not found for ${subtopicId}`);

  const valStartIdx = maIdx + maKey.length;
  
  // Find closing unescaped double quote
  let valEndIdx = -1;
  for (let i = valStartIdx; i < content.length; i++) {
    if (content[i] === '"' && content[i - 1] !== '\\') {
      valEndIdx = i;
      break;
    }
  }
  
  if (valEndIdx === -1) throw new Error(`Closing quote not found for ${subtopicId}`);

  const before = content.substring(0, valStartIdx);
  const after = content.substring(valEndIdx);
  const escapedAnswer = escapeForJSON(newAnswer);
  
  return before + escapedAnswer + after;
}

// Helper to replace the modela inside questions.js
function replaceExamsModelAnswer(content, questionId, newAnswer) {
  let qIdx = content.indexOf(`"${questionId}"`);
  if (qIdx === -1) {
    qIdx = content.indexOf(`['${questionId}']`);
  }
  if (qIdx === -1) {
    qIdx = content.indexOf(`["${questionId}"]`);
  }
  if (qIdx === -1) {
    qIdx = content.indexOf(`${questionId}:`);
  }
  
  if (qIdx === -1) throw new Error(`Question ${questionId} not found in questions.js`);

  const maKey = 'modela: "';
  const maIdx = content.indexOf(maKey, qIdx);
  if (maIdx === -1) throw new Error(`modela key not found for ${questionId}`);

  const valStartIdx = maIdx + maKey.length;
  
  // Find closing unescaped double quote
  let valEndIdx = -1;
  for (let i = valStartIdx; i < content.length; i++) {
    if (content[i] === '"' && content[i - 1] !== '\\') {
      valEndIdx = i;
      break;
    }
  }
  
  if (valEndIdx === -1) throw new Error(`Closing quote not found for ${questionId}`);

  const before = content.substring(0, valStartIdx);
  const after = content.substring(valEndIdx);
  const escapedAnswer = escapeForJSON(newAnswer);
  
  return before + escapedAnswer + after;
}

// ==========================================
// 1. LESSON ANSWERS (16 Subtopics)
// ==========================================
export const LESSON_ANSWERS = {
  subtopic_1_1: 
`Source D is highly useful for showing the response of activists and the direct police criminalization of peaceful protestors in the South. For example, the photograph depicts "Rosa Parks standing calm and dignified" while being fingerprinted by a police officer in uniform. This content is highly useful because it is supported by my contextual knowledge that [[Rosa Parks' refusal to give up her seat in December 1955 sparked the Montgomery Bus Boycott, which lasted 381 days and successfully desegregated buses]], which confirms that the photograph is an accurate representation of the active resistance and the direct police intimidation that activists had to overcome in the Southern states. {{The provenance strengthens the source's utility because it was taken on 22 February 1956, during the height of the boycott, making it a reliable, contemporary visual record of the state's attempt to criminalize and intimidate boycott leaders. However, its usefulness is slightly limited because it is a staged publicity photo that only captures a single moment of arrest, failing to show the SCLC's broader legal strategy.}}\n\nSource E is highly useful for demonstrating the systemic, official nature of segregation in public facilities in the 1950s. The photograph shows a wooden sign reading "COLORED WAITING ROOM" hanging above a public entrance. This content's utility is supported by my knowledge that [[Jim Crow laws in the Southern states officially enforced segregation in transit, waiting rooms, and restaurants, creating separate and unequal conditions]], which confirms that the sign is an accurate representation of how segregation was physically and legally enforced in Southern public spaces. {{The provenance, taken in the Southern United States in the early 1950s, makes the source extremely useful because it provides direct, unedited evidence of state-sanctioned segregation infrastructure. However, it is less useful because it only shows the sign itself, failing to document the personal experiences of the Black passengers who suffered under segregation or the active resistance against it.}}`,

  subtopic_1_2:
`Source D is highly useful for showing the intense social opposition and grassroots white resistance to school integration. The photograph depicts an "angry white crowd" of students and adults protesting, with some carrying signs reading "Keep Central High Clean". This content is highly useful because it is supported by my contextual knowledge that [[when the Little Rock Nine attempted to integrate Central High School in September 1957, they faced violent, threatening white mobs who surrounded the school]], which confirms that the source is an extremely useful record of the deep-seated racial hostility and active resistance to integration in the South. {{The provenance, taken outside Central High in September 1957, makes the source highly useful because it captures the raw, authentic hostility of the segregationists at the exact moment of the crisis. However, it is less useful because it only represents the vocal extremist protesters, failing to show the moderate white citizens or the experiences of the Black students inside the school.}}\n\nSource E is highly useful for showing the scale of the state and military conflict required to override this local segregationist opposition. The photograph shows "armed federal troops standing in single file" holding bayonets. This content's usefulness is supported by my knowledge that [[Governor Orval Faubus used the National Guard to block the Black students, forcing President Eisenhower to send 1,000 soldiers of the 101st Airborne Division to enforce integration]], which explains why such heavy military presence was necessary to protect the students. {{The provenance of late September 1957 makes the source extremely useful because it documents the historic federal intervention needed to uphold the Constitution. However, it is slightly less useful because it portrays a staged, orderly military patrol, which hides the constant, daily psychological harassment the students endured from white classmates inside the classrooms.}}`,

  subtopic_1_3:
`Source D is highly useful for showing the spiritual leadership and religious solidarity that sustained the boycott. The photograph shows Martin Luther King Jr. "speaking passionately from a pulpit" to a packed church of Black citizens. This content is highly useful because it is supported by my contextual knowledge that [[the Montgomery Improvement Association (MIA) held regular mass meetings in local churches to coordinate strategy, maintain non-violent discipline, and raise funds for the boycott]], which confirms that the source is an accurate representation of the central role the church played as the movement's organizational and spiritual hub. {{The provenance of late 1955 makes the source highly useful because it captures the central role of the Black church at the very beginning of the boycott. However, it is less useful because it focuses solely on Dr. King's charismatic leadership, omitting the crucial organizing work of figures like Jo Ann Robinson and the Women's Political Council.}}\n\nSource E is highly useful for showing the direct police criminalization of peaceful protestors and the individual courage of boycott leaders. The photograph depicts "Rosa Parks standing calmly" while a police officer in uniform applies ink to her fingers for fingerprinting. This content is highly useful because it is supported by my contextual knowledge that [[the local authorities in Montgomery attempted to break the boycott by indicting and arresting over 80 leaders, including Rosa Parks and MLK, under an old anti-conspiracy law in February 1956]], which confirms that the photograph is an accurate representation of the state's efforts to legally harass and intimidate civil rights activists. {{The provenance, taken on 22 February 1956 during the height of the Montgomery Bus Boycott, strengthens its utility because it captures a real-time record of state-level intimidation. However, it is slightly limited because it is a staged publicity photo taken for the press, failing to represent the daily grassroots efforts of thousands of ordinary boycotters who walked or carpooled.}}`,

  subtopic_1_4:
`Source D is highly useful for showing the official, legalistic methods of resistance deployed by Southern politicians to defy integration. The photograph depicts "a group of Southern Senators and Congressmen signing the Southern Manifesto", pledging to use all lawful means to resist federal rulings. This content is highly useful because it is supported by my contextual knowledge that [[in March 1956, over 100 Southern politicians signed the Southern Manifesto to coordinate resistance, falsely claiming the Supreme Court's Brown ruling was an abuse of judicial power]], which confirms that the photograph is an accurate representation of how Southern elites lent political legitimacy to segregation. {{The provenance makes the source highly useful because it documents a historic moment of political mobilization in March 1956, showing the unity of Southern lawmakers. However, it is limited because it only captures a public signing ceremony, concealing the illegal, violent tactics and economic intimidation that these same state authorities quietly condoned on the ground.}}\n\nSource E is highly useful for showing the violent and physical intimidation used by extremist groups to enforce segregation. The photograph depicts "dozens of Klansmen in white robes and pointed hoods marching" down a street while police stand by. This content's utility is supported by my knowledge that [[the Ku Klux Klan experienced a major revival in the 1950s, using bombings, beatings, and lynchings to terrorize civil rights workers with local police collusion]], which confirms the accuracy of the source as a record of KKK activity. {{The provenance, showing a KKK march in 1957, makes the source highly useful because it shows the public, unchecked presence of white supremacist groups. However, it is less useful because it only captures a public parade, failing to document the illegal, clandestine nature of KKK violence and their collusion with local police.}}`,

  subtopic_2_1:
`Source D is highly useful for showing the non-violent direct action tactics used by student activists to challenge retail segregation. The photograph shows "four Black college students sitting quietly" on counter stools while white teenagers pour sugar on them. This content is highly useful because it is supported by my knowledge that [[the Greensboro sit-in of February 1960 at Woolworth's sparked a massive sit-in movement across the South, demonstrating SNCC's commitment to non-violent resistance]], which validates that the photograph is an accurate representation of the physical harassment activists endured to expose Southern bigotry. {{The provenance, taken in February 1960, makes the source highly useful because it provides an authentic, contemporary record of the protests. However, it is less useful because it only shows the counter itself, omitting the wider economic boycott of the store organized by the local community that forced integration.}}\n\nSource E is highly useful for showing the extreme level of state resistance to university integration and the federal intervention needed to override it. The photograph depicts James Meredith walking "flanked by several tall, serious US Marshals" wearing helmets. This content's utility is supported by my knowledge that [[Governor Ross Barnett defied federal orders, prompting President Kennedy to send 30,000 troops and US Marshals to force the integration of the University of Mississippi in October 1962, sparking riots that killed two people]], which explains the military necessity of using armed guards to protect a single Black student. {{The provenance of October 1962 makes the source extremely useful because it visually documents the armed federal power needed to protect Black rights. However, it is less useful because it depicts a controlled walk, failing to capture the chaos and violence of the Ole Miss riot itself.}}`,

  subtopic_2_2:
`Source D is highly useful for showing the massive scale, unity, and public impact of non-violent civil rights campaigns. The photograph depicts Martin Luther King Jr. "looking out over a massive crowd of over 250,000 demonstrators" surrounding the reflecting pool. This content's utility is supported by my knowledge that [[the March on Washington in August 1963 was a key moment of multi-racial unity that put pressure on the Kennedy administration to pass civil rights laws]], which confirms the effectiveness of non-violent mobilization in capturing national attention. {{The provenance of 28 August 1963 makes the source highly useful because it captures the peak of the movement's public mobilization. However, it is less useful because it highlights a single speech, obscuring the deep strategic disagreements between SNCC, SCLC, and other coalition members behind the scenes.}}\n\nSource E is highly useful for showing the political and legislative outcomes of grassroots non-violent campaigns. The photograph shows President Johnson "handing a commemorative pen to Martin Luther King Jr." and other leaders at the desk. This content is highly useful because it is supported by my knowledge that [[the legislative alliance between LBJ and civil rights leaders led to the passage of the Voting Rights Act of 1965, which banned literacy tests and authorized federal registrars]], which proves that grassroots moral pressure successfully forced federal reform. {{The provenance of 6 August 1965 makes the source extremely useful because it documents the formal signing of this landmark act. However, it is less useful because it portrays a harmonious political consensus, hiding the intense pressure, political caution, and FBI surveillance that Johnson's administration directed at civil rights leaders.}}`,

  subtopic_2_3:
`Source D is highly useful for understanding the intellectual shift toward self-defense and militancy. The photograph shows Malcolm X pointing to a newspaper headline that reads "Blacks Must Defend Themselves Against Klan Terror!". This content is highly useful because it is supported by my knowledge that [[Malcolm X rejected SCLC's non-violent integration, advocating Black nationalism, economic self-reliance, and self-defense 'by any means necessary' to appeal to Northern urban Black communities]], which confirms that the source is an accurate representation of his teachings and his rejection of MLK's non-violent approach. {{The provenance of 1964 makes the source highly useful because it documents how Malcolm X used print media to directly challenge MLK's non-violent orthodoxy. However, it is less useful because it is a posed, strategic media photograph designed to project militancy, rather than showing Malcolm's complex intellectual evolution.}}\n\nSource E is highly useful for showing how Black Power and militancy were institutionalized by student groups in the late 1960s. The photograph depicts a "column of Black Panther members wearing black leather jackets, black berets" marching in formation. This content's usefulness is supported by my knowledge that [[the Black Panther Party, founded in 1966 in Oakland, California, rejected integration and police brutality, calling for armed patrols and community self-reliance]], which validates the source as a visual representation of their militant discipline and rejection of pacifism. {{The provenance of 1968 makes the source extremely useful because it visually captures the disciplined, militaristic style of Black Power. However, it is less useful because it focuses on their armed, militant appearance, ignoring their extensive community welfare programs, such as free breakfasts for children.}}`,

  subtopic_2_4:
`Source D is highly useful for showing the scale of violence, property destruction, and military deployment during the urban riots. The photograph shows "armed National Guardsmen standing in front of burning storefronts" in Detroit. This content is highly useful because it is supported by my knowledge that [[the Detroit Riot of July 1967 resulted in 43 deaths, over 1,000 injuries, and prompted the Kerner Commission to investigate the systemic racism and poverty in Northern ghettos]], which explains the military necessity of deploying the National Guard. {{The provenance of July 1967 makes the source highly useful because it provides an authentic, contemporary record of the military force needed to suppress urban rebellions. However, it is less useful because it focuses on the law-and-order response, failing to depict the underlying causes of the riot, such as police brutality and housing discrimination.}}\n\nSource E is highly useful for showing the immediate political and emotional impact of MLK's death on Black Americans. The photograph shows a "large crowd... carrying signs that read 'Honor King: End Racism Now'" with smoldering buildings in the background. This content's utility is supported by my knowledge that [[the assassination of Martin Luther King Jr. on 4 April 1968 sparked violent riots in over 100 cities, marking the end of the non-violent civil rights era]], which confirms the immediate transition from grief to civil unrest across American cities. {{The provenance of April 1968 in Washington D.C. makes the source extremely useful because it captures the national grief and outrage. However, it is less useful because it portrays a peaceful march, failing to represent the violent riots and arson that occurred in Washington D.C. at the same time.}}`,

  subtopic_3_1:
`Source D is highly useful for showing President Diem's authoritarian methods and his reliance on military forces to maintain power. The photograph shows "Diem standing in an open-top car, reviewing rows of South Vietnamese soldiers" carrying US-supplied weapons. This content is highly useful because it is supported by my knowledge that [[the US supported Diem's anti-communist regime with massive military aid and advisors from 1955, despite his corruption, nepotism, and lack of peasant support]], which explains the militaristic nature of Diem's control. {{The provenance of October 1957 makes the source highly useful because it illustrates how the regime projected military authority to hide its internal weaknesses. However, it is less useful because it shows a highly staged state event in Saigon, concealing the lack of peasant support and the growing communist insurgency in the countryside.}}\n\nSource E is highly useful for showing the scale of religious opposition that undermined Diem's regime. The photograph shows a "massive crowd of Buddhist monks and nuns sitting in a street, holding banners reading 'Stop Religious Persecution!'". This content's utility is supported by my knowledge that [[Diem's favoritism toward the Catholic minority and suppression of the Buddhist majority sparked the Buddhist Crisis of 1963, including self-immolations that destroyed the regime's international legitimacy]], which confirms that the source represents the broad civil opposition that made the regime collapse-prone. {{The provenance of June 1963 makes the source extremely useful because it captures the public crisis that forced the US to support a military coup against Diem in November 1963. However, it is less useful because it only captures the peaceful protests, omitting the violent police raids on pagodas.}}`,

  subtopic_3_2:
`Source D is highly useful for showing the US naval presence that served as the trigger for direct combat escalation. The photograph shows the "USS Maddox traveling through calm seas" with gun turrets aimed toward the horizon. This content is highly useful because it is supported by my knowledge that [[the Gulf of Tonkin incidents of August 1964 led Congress to pass the Gulf of Tonkin Resolution, giving President Johnson a 'blank check' to escalate US military involvement]], which confirms the naval buildup that preceded the congressional mandate. {{The provenance of August 1964 makes the source highly useful because it documents the actual vessel involved in the clashes. However, it is less useful because it shows a calm, routine patrol, failing to clarify the disputed and confusing details of the attacks.}}\n\nSource E is highly useful for showing the transition to full combat operations and the deployment of ground troops. The photograph shows "US Marines carrying heavy backpacks and rifles wading through shallow water" onto Da Nang beach. This content's utility is supported by my knowledge that [[the landing of the 9th Marine Expeditionary Brigade in March 1965 marked the official start of the US ground war, with troop levels rising to 184,000 by the end of 1965]], which confirms that the photograph captures the historic landing that marked the end of the advisory phase. {{The provenance of 8 March 1965 makes the source extremely useful because it captures the historical moment of transition to direct combat. However, it is less useful because the presence of local women handing out flowers was a staged public relations event, hiding the hostile, muddy reality of combat that the Marines would soon face.}}`,

  subtopic_3_3:
`Source D is highly useful for showing the tactical and physical challenges that US combat patrols faced. The photograph shows a US soldier "wading waist-deep through muddy swamp water in dense jungle" holding his rifle high. This content's utility is supported by my knowledge that [[US Search and Destroy tactics designed to find the Vietcong faced terrain problems and ambush vulnerability, as the Vietcong used booby traps and the jungle environment to neutralize US technology]], which explains the physical and psychological exhaustion depicted. {{The provenance of 1967 makes the source highly useful because it offers a realistic, gritty look at the brutal environmental conditions. However, it is less useful because it focuses on a single soldier's exhaustion, failing to show the high civilian casualties and destruction of villages that search-and-destroy missions often caused.}}\n\nSource E is highly useful for showing the chemical warfare tactics used by the US to counter these environmental challenges. The photograph shows "C-123 military transport planes... releasing thick white chemical trails of Agent Orange" over dense forest. This content is highly useful because it is supported by my knowledge that [[Operation Ranch Hand sprayed millions of gallons of herbicides to strip jungle cover and destroy crops, which poisoned food supplies and alienated the peasant population]], which confirms the systemic scale of environmental destruction that alienated the local population. {{The provenance of 1966 makes the source extremely useful because it documents the systematic, industrial scale of chemical defoliation. However, it is less useful because it presents a clean, aerial view of the spraying, omitting the devastating health consequences, birth defects, and political backlash among Vietnamese peasants.}}`,

  subtopic_3_4:
`Source D is highly useful for showing the public relations campaign used to justify Vietnamization. The photograph shows "Nixon standing in a crowd of smiling US soldiers" in combat uniforms. This content's utility is supported by my knowledge that [[President Nixon introduced 'Vietnamization' in 1969 to gradually withdraw US combat troops while shifting responsibility to the ARVN, seeking 'peace with honor' to satisfy the public]], which explains the positive, supportive image projected by the President. {{The provenance of July 1969 makes the source highly useful because it illustrates the presidential photo opportunity used to project troop support. However, it is less useful because it is a carefully managed event, masking the low morale, drug use, and growing anti-war sentiment among the soldiers in the field.}}\n\nSource E is highly useful for showing that Vietnamization actually expanded the geographical scope of the war. The photograph shows "ARVN soldiers running past a burning tank on a dirt road in Cambodia" with helicopters overhead. This content is highly useful because it is supported by my knowledge that [[Nixon ordered the invasion of Cambodia in May 1970 to destroy communist sanctuaries and supply lines, which failed to secure South Vietnam and sparked massive protests at Kent State]], which confirms that ARVN relied heavily on US air support and regional incursions rather than independent ground strength. {{The provenance of May 1970 makes the source extremely useful because it shows ARVN troops in active combat. However, it is less useful because it portrays a successful tactical advance, failing to show the strategic failure of the campaign or the ARVN's heavy reliance on US air power.}}`,

  subtopic_4_1:
`Source D is highly useful for showing the youth-led, confrontational nature of the anti-war movement. The photograph shows "young demonstrators carrying peace signs... facing a wall of military police". This content's utility is supported by my knowledge that [[the Pentagon protest of October 1967 reflected the rapid growth of the anti-war movement as the draft escalated, with draft card burning and peaceful marches becoming common]], which confirms the growing polarization and student involvement at this time. {{The provenance of October 1967 makes the source highly useful because it captures the direct, non-violent confrontation with military authority. However, it is less useful because it focuses on a single demonstration in Washington D.C., failing to show the wider, working-class opposition or moderate critics of the war.}}\n\nSource E is highly useful for showing the lethal escalation of state suppression of student protests on campus. The photograph shows a "line of National Guard soldiers... aimed toward them, holding rifles" at Kent State. This content is highly useful because it is supported by my knowledge that [[the Kent State shootings of May 1970, where National Guardsmen killed four students protesting the invasion of Cambodia, triggered a strike of 4 million students nationwide]], which validates the high tension and physical danger student protesters faced. {{The provenance of May 1970 makes the source extremely useful because it documents the tense standoff just before the shooting. However, it is less useful because it captures the standoff, failing to explain the panic, chaos, and nationwide student strike that followed.}}`,

  subtopic_4_2:
`Source D is highly useful for showing the organized public support for President Nixon's policies. The photograph shows citizens holding signs reading "Support Our President" and "Silent Majority Speaks". This content's usefulness is supported by my knowledge that [[President Nixon's November 1969 speech appealed to the 'Silent Majority'—the patriotic, law-abiding middle-class citizens who did not join protests—to politically counter the anti-war movement]], which confirms that Nixon's rhetoric successfully mobilized a visible, pro-government counter-protest. {{The provenance of 1970 makes the source highly useful because it proves that pro-war citizens actively adopted Nixon's rhetoric. However, it is less useful because it is a pro-war rally, which may exaggerate the active support of the average citizen who was simply silent or disengaged.}}\n\nSource E is highly useful for showing the working-class basis of this pro-war support and the polarization of the home front. The photograph shows "construction workers... marching... banners reading 'USA All the Way'". This content is highly useful because it is supported by my knowledge that [[the Hard Hat Riots of May 1970, where construction workers attacked students protesting the Kent State shootings in New York City, revealed deep class divisions on the home front]], which explains why working-class patriotism clashed violently with student pacifism. {{The provenance of May 1970 makes the source extremely useful because it documents the intense, working-class backlash against student protestors. However, it is less useful because it shows workers marching, concealing the complex economic anxieties and union politics that also drove their opposition to student demonstrators.}}`,

  subtopic_4_3:
`Source D is highly useful for showing the formal, diplomatic conclusion of US military involvement in Vietnam. The photograph shows "diplomats sitting around a massive circular table... signing the official treaty" in Paris. This content's utility is supported by my knowledge that [[the signing of the Paris Peace Accords in January 1973 ended direct US military involvement, securing the withdrawal of US troops and the return of POWs]], which confirms the diplomatic settlement that allowed a face-saving exit for the US. {{The provenance of 27 January 1973 makes the source highly useful because it documents the formal legal conclusion of the war. However, it is less useful because it portrays a polished, peaceful diplomatic consensus, ignoring the secret negotiations, pressure on South Vietnamese President Thieu, and the fact that fighting continued between North and South.}}\n\nSource E is highly useful for showing the chaotic, real-world failure of the peace treaty and the collapse of Vietnamization. The photograph shows a "long line of people climbing a ladder onto the roof... to board a CIA Huey helicopter" at the US embassy. This content is highly useful because it is supported by my knowledge that [[the Fall of Saigon in April 1975, when North Vietnamese forces captured the capital and South Vietnam surrendered, marked the final failure of US containment policy in Indochina]], which explains why the evacuation had to be conducted in such a panic. {{The provenance of 29 April 1975 makes the source extremely useful because it provides a raw, iconic visual record of defeat. However, it is less useful because it focuses on the panic at the evacuation point, failing to capture the military campaigns and political decisions that led to the final collapse.}}`,

  subtopic_4_4:
`Source D is highly useful for showing the tactical and military challenges that caused US failure. The photograph shows several soldiers "wading through thick mud and reeds in a swamp" in Vietnam. This content is highly useful because it is supported by my knowledge that [[US conventional advantages in heavy armor and firepower were neutralized by the difficult swamp and jungle terrain, which favored Vietcong guerrilla warfare and ambush tactics]], which confirms the environmental difficulties that bogged down US infantry. {{The provenance of 1968 makes the source highly useful because it visually represents the physical and tactical quagmire that US combat patrols faced. However, it is less useful because it only shows the tactical environment, failing to represent the strategic failures of the search-and-destroy policy or the political instability in Saigon.}}\n\nSource E is highly useful for showing the political and moral collapse of the war effort at home. The photograph shows "veterans... throwing their military medals and ribbons over a wire fence" in front of the Capitol. This content's utility is supported by my knowledge that [[the Vietnam Veterans Against the War (VVAW) protests of 1971, which included veterans testifying about war crimes, severely damaged the government's moral credibility]], which confirms that even those who fought had turned against the conflict, destroying its domestic legitimacy. {{The provenance of 1971 in Washington D.C. makes the source extremely useful because it shows the deep moral and political disillusionment of the soldiers who fought. However, it is less useful because it represents the views of highly politicized, activist veterans, rather than the silent majority of returning soldiers who did not join protests.}}`
};

// ==========================================
// 2. EXAM ANSWERS (15 questions)
// ==========================================
export const EXAM_ANSWERS = {
  q3_1: 
`Source B is highly useful for demonstrating the legal litigation strategy of the NAACP. The content highlights how their legal campaigns are "finally bearing fruit" by targeting segregated institutions, allowing them to successfully challenge segregation in courts. This content is highly useful because it is supported by my contextual knowledge that [[the NAACP won the Brown v. Board of Education case in 1954, declaring segregated schools unconstitutional, and had previously won Sweatt v. Painter in 1950]], which confirms that their legal strategy successfully dismantled segregation's constitutional basis. {{The provenance makes the source more useful because it is an internal, private report written by lead lawyer Thurgood Marshall in 1953. Since it was not intended for public propaganda, it represents a highly reliable, realistic assessment of NAACP strategy and confidence just before their major legal victories.}}\n\nSource C is highly useful for showing the direct action methods of CORE and the severe grassroots opposition they faced. The activist describes staging a "peaceful sit-in at the downtown lunch counter" but being met with a white mob that "spat on, kicked, and dragged" them while police stood by. This content's utility is supported by my knowledge that [[CORE pioneered non-violent direct action, including lunch counter sit-ins, in Northern and Midwestern cities in the 1940s and 1950s, though they faced intense local resistance]], which verifies that changing federal laws did not automatically protect activists from local hostility. {{The provenance increases its usefulness because it is a first-hand account by a CORE activist published in a contemporary newsletter in 1952. While the newsletter was designed to motivate members, which might emphasize the drama, it is extremely useful for revealing the immediate physical dangers, emotional frustrations, and reliance on alternative media to publicize their struggle.}}`,

  q3_2:
`Source B is highly useful for showing the persistent racial inequalities and lack of economic progress by the late 1960s. The report warns that the nation is "moving toward two societies, one black, one white—separate and unequal" due to the maintaining of segregated ghettos. This content is highly useful because it is supported by my contextual knowledge that [[despite civil rights legislation, deep-seated economic inequality and police brutality led to major race riots in Watts (1965), Newark, and Detroit (1967), showing the limits of legal progress]], which confirms that the report is an accurate and typical representation of the deep social divide. {{The provenance strengthens its usefulness because it is an official government-commissioned report from the Kerner Commission in 1968. Since it was compiled by moderate white politicians who concluded that white institutional racism was responsible, it provides a highly reliable, objective official admission of the limits of legal progress.}}\n\nSource C is highly useful for demonstrating the significant political and social achievements of the civil rights movement by the mid-1970s. The politician asserts that the changes are "monumental" because the "Whites Only" signs are gone and Black citizens are electing "black mayors in major American cities". This content's utility is supported by my knowledge that [[the Voting Rights Act of 1965 led to a dramatic increase in Black political representation and the election of Black mayors, while Nixon's affirmative action policies opened corporate hiring]], which confirms that the politician's optimism is based on tangible structural progress. {{The provenance increases its usefulness because it is a contemporary interview from 1974 with a politician active in the movement. While he may have a bias toward highlighting political success to justify his career, it is highly useful for showing the perspective of Black leaders who successfully transitioned from street activism to institutional political power.}}`,

  p_2019_q3:
`Source B is highly useful for showing the SCLC's strategic methods of non-violent mobilization and church-based organization. The author reports that King spoke to "several thousand people" in a church, asking them to "remain non-violent" and to ride the buses again under a new spirit of dignity. This content is highly useful because it is supported by my contextual knowledge that [[the Montgomery Improvement Association, led by MLK, organized regular mass meetings in Black churches to sustain community morale and enforce non-violent discipline during the 381-day bus boycott]], which confirms that the newsletter provides an accurate representation of the movement's religious foundation. {{The provenance increases the source's utility because it is an internal newsletter published in early 1956. While it was intended as a motivational piece that downplays internal divisions or exhaustion, it is highly useful for showing the official rhetoric used to keep the community united during a prolonged crisis.}}\n\nSource C is highly useful for demonstrating the legal opposition and hostile reactions of local white authorities to the boycott. Mayor Gayle declares that the boycott is "an illegal economic conspiracy" and that they have "no intention of negotiating with lawbreakers." This content's usefulness is supported by my knowledge that [[Montgomery city officials used local laws to indict MLK and 80 other boycott leaders for disrupting lawful business, attempting to crush the protest through legal intimidation]], which confirms that the Mayor's public resistance was typical of Southern political elites. {{The provenance of a statement by the Montgomery Mayor in January 1956 makes the source extremely useful because it captures the official segregationist position at the height of the boycott, showing their determination to defend the Jim Crow system. However, it is less useful because it frames the dispute purely as a legal matter, hiding the extra-legal violence and KKK intimidation that authorities tolerated on the ground.}}`,

  p_2020_q3:
`Source B is highly useful for showing the SCLC's strategic methods of non-violent mobilization and church-based organization. The author reports that King spoke to "several thousand people" in a church, asking them to "remain non-violent" and to ride the buses again under a new spirit of dignity. This content is highly useful because it is supported by my contextual knowledge that [[the Montgomery Improvement Association, led by MLK, organized regular mass meetings in Black churches to sustain community morale and enforce non-violent discipline during the 381-day bus boycott]], which confirms that the newsletter provides an accurate representation of the movement's religious foundation. {{The provenance increases the source's utility because it is an internal newsletter published in early 1956. While it was intended as a motivational piece that downplays internal divisions or exhaustion, it is highly useful for showing the official rhetoric used to keep the community united during a prolonged crisis.}}\n\nSource C is highly useful for demonstrating the legal opposition and hostile reactions of local white authorities to the boycott. Mayor Gayle declares that the boycott is "an illegal economic conspiracy" and that they have "no intention of negotiating with lawbreakers." This content's usefulness is supported by my knowledge that [[Montgomery city officials used local laws to indict MLK and 80 other boycott leaders for disrupting lawful business, attempting to crush the protest through legal intimidation]], which confirms that the Mayor's public resistance was typical of Southern political elites. {{The provenance of a statement by the Montgomery Mayor in January 1956 makes the source extremely useful because it captures the official segregationist position at the height of the boycott, showing their determination to defend the Jim Crow system. However, it is less useful because it frames the dispute purely as a legal matter, hiding the extra-legal violence and KKK intimidation that authorities tolerated on the ground.}}`,

  p_2022_q3:
`Source B is highly useful for showing the SCLC's strategic methods of non-violent mobilization and church-based organization. The author reports that King spoke to "several thousand people" in a church, asking them to "remain non-violent" and to ride the buses again under a new spirit of dignity. This content is highly useful because it is supported by my contextual knowledge that [[the Montgomery Improvement Association, led by MLK, organized regular mass meetings in Black churches to sustain community morale and enforce non-violent discipline during the 381-day bus boycott]], which confirms that the newsletter provides an accurate representation of the movement's religious foundation. {{The provenance increases the source's utility because it is an internal newsletter published in early 1956. While it was intended as a motivational piece that downplays internal divisions or exhaustion, it is highly useful for showing the official rhetoric used to keep the community united during a prolonged crisis.}}\n\nSource C is highly useful for demonstrating the legal opposition and hostile reactions of local white authorities to the boycott. Mayor Gayle declares that the boycott is "an illegal economic conspiracy" and that they have "no intention of negotiating with lawbreakers." This content's usefulness is supported by my knowledge that [[Montgomery city officials used local laws to indict MLK and 80 other boycott leaders for disrupting lawful business, attempting to crush the protest through legal intimidation]], which confirms that the Mayor's public resistance was typical of Southern political elites. {{The provenance of a statement by the Montgomery Mayor in January 1956 makes the source extremely useful because it captures the official segregationist position at the height of the boycott, showing their determination to defend the Jim Crow system. However, it is less useful because it frames the dispute purely as a legal matter, hiding the extra-legal violence and KKK intimidation that authorities tolerated on the ground.}}`,

  p_2023_q3:
`Source B is highly useful for showing how US military tactics alienated the civilian population in South Vietnam. The report states that heavy reliance on "search-and-destroy operations and chemical defoliants has created hundreds of thousands of refugees" and is driving peasants "directly into the arms of the enemy". This content's utility is supported by my knowledge that [[tactics like search-and-destroy and the chemical spraying of Agent Orange under Operation Ranch Hand alienated the rural population, making it impossible to win the hearts and minds campaign]], which confirms that US tactics actively fueled the communist insurgency. {{The provenance strengthens its usefulness because it is an official report by a US Senate Subcommittee in 1968. Since it is a self-critical government investigation, it provides a highly reliable, objective contemporary record of the counterproductive nature of US military operations.}}\n\nSource C is highly useful for understanding the Vietcong perspective on US military actions and their effect on peasant recruitment. The veteran recalls that because US troops "did not know who the enemy was", they treated everyone as Vietcong and "burned our huts and killed our livestock. This made even the quietest peasants want to fight". This content is highly useful because it is supported by my knowledge that [[the Vietcong guerrilla strategy relied on hiding among civilians, which led frustrated US soldiers to treat all villagers as hostile, driving many peasants to support the communists]], which explains how US high-firepower tactics actively drove recruits to the VC. {{The provenance of a 1985 interview with a Vietcong veteran makes it useful for providing an insider's recollection of the conflict. While it may contain retrospective communist propaganda, it is highly useful for explaining how US tactical errors strengthened the insurgency.}}`,

  p_2024_q3:
`Source B is highly useful for showing the psychological strain and tactical difficulties faced by US ground forces in Vietnam. The soldier writes about patrolling in circles through a swamp where they "cannot see the enemy, but we know they are there" and are losing men to mines, noting that they are "fighting a shadow, and we are losing our minds". This content's utility is supported by my knowledge that [[the Vietcong used guerrilla warfare, tunnels, and booby traps in the Mekong Delta, which neutralised US conventional firepower and caused severe psychological stress for soldiers]], which explains the intense exhaustion and fear expressed in his diary. {{The provenance, a personal diary entry from 1967, makes the source extremely useful. Because it was written privately for himself and not for military censors or the public, it represents a highly reliable, authentic record of the daily physical and psychological toll of guerrilla warfare.}}\n\nSource C is highly useful for understanding the military strategy and resilience of the communist forces. The commander explains that they "used the jungle and our tunnels to neutralise their air power" and aimed to "keep fighting until the American public grew tired of the war". This content is highly useful because it is supported by my contextual knowledge that [[the communists waged a war of attrition, utilizing the Cu Chi tunnels and jungle cover to survive US bombing, counting on growing anti-war sentiment in the US to force a withdrawal]], which confirms the accuracy of the commander's strategic recollections. {{The provenance of a post-war interview with a North Vietnamese commander in 1982 makes it useful because it offers an official retrospective explanation of their victory. While he has a natural interest in emphasizing their ideological determination and heroic sacrifice, it is highly useful for showing the strategic patience that allowed them to defeat a technologically superior superpower.}}`,

  p_2025_q3:
`Source B is highly useful for showing the student perspective and moral outrage surrounding the Kent State shootings. The student describes the rally as a "peaceful rally against the President's illegal invasion of Cambodia" and accuses the National Guard of firing "live ammunition directly into the crowd of unarmed students." This content is highly useful because it is supported by my contextual knowledge that [[the Kent State shootings in May 1970, where National Guardsmen fired 67 rounds into a crowd, killing four and wounding nine students, became a symbol of extreme government suppression]], which confirms that the eyewitness account captures the authentic feeling of shock and alienation. {{The provenance of a student magazine published in May 1970 increases its usefulness because it provides an immediate, unedited record of student anger. However, it is limited because it represents a highly partisan student viewpoint that ignores the pre-existing tensions, arson of the ROTC building, and rock-throwing that preceded the guard's reaction.}}\n\nSource C is highly useful for understanding the Nixon administration's perspective and their framing of anti-war protesters to maintain conservative support. Nixon asserts that "when students resort to throwing rocks... tragedy is inevitable" and labels them "violent, anti-American radicals." This content's usefulness is supported by my knowledge that [[Nixon actively appealed to the 'Silent Majority' of patriotic, law-abiding Americans who resented radical student protesters, using a law-and-order stance to justify the war and police actions]], which confirms that the speech is typical of Nixon's political strategy. {{The provenance of a televised presidential speech in May 1970 is highly useful because it shows how the government officially sought to manage the crisis and turn public opinion against the student demonstrators. However, it is less useful because it is a political speech designed to deflect blame from the National Guard and maintain support for Nixon's Cambodia policy.}}`,

  mock_exam_1:
`Source B is highly useful for showing the hostile reaction of northern white working-class residents to King's campaign. The resident complains that King "stirred up trouble where there was none" and that the marches "just made people angry" and caused riots. This content is highly useful because it is supported by my contextual knowledge that [[King's Chicago campaign in 1966 targeted housing segregation, which faced fierce opposition from white working-class neighborhoods who feared falling property values and integration]], which confirms that the source is an accurate representation of the defensive white backlash in Chicago. {{The provenance makes this source useful because it is an interview published in a local newspaper shortly after the marches in 1966. While it reflects a narrow, defensive viewpoint that downplays systemic northern racism, it is highly useful for showing the immediate resentment and racial defensiveness of Chicago's white residents who refused to see their city as segregated.}}\n\nSource C is highly useful for demonstrating the extreme violence that civil rights protestors faced in the North. The activist describes marching through Cicero and being met with "bricks and bottles from a white mob", noting that the hatred was "worse than anything he had faced in Mississippi". This content's utility is supported by my knowledge that [[during the SCLC marches in Chicago suburbs like Cicero and Marquette Park, protestors were met by thousands of violent white residents throwing bricks, showing that Northern housing segregation was maintained with the same brutality as Southern Jim Crow]], which verifies that northern segregation was actively defended by grassroots violence. {{The provenance strengthens the source's usefulness because it is a first-hand account by an SCLC activist who participated in the march. While he has an interest in emphasizing the violence to expose Northern racism to the world, it is highly useful for capturing the physical danger and disillusionment of the campaigners.}}`,

  mock_exam_2:
`Source B is highly useful for showing the student perspective and moral outrage surrounding the Kent State shootings. The student describes the rally as a "peaceful rally against the President's illegal invasion of Cambodia" and accuses the National Guard of firing "live ammunition directly into the crowd of unarmed students." This content is highly useful because it is supported by my contextual knowledge that [[the Kent State shootings in May 1970, where National Guardsmen fired 67 rounds into a crowd, killing four and wounding nine students, became a symbol of extreme government suppression]], which confirms that the eyewitness account captures the authentic feeling of shock and alienation. {{The provenance of a student magazine published in May 1970 increases its usefulness because it provides an immediate, unedited record of student anger. However, it is limited because it represents a highly partisan student viewpoint that ignores the pre-existing tensions, arson of the ROTC building, and rock-throwing that preceded the guard's reaction.}}\n\nSource C is highly useful for understanding the Nixon administration's perspective and their framing of anti-war protesters to maintain conservative support. Nixon asserts that "when students resort to throwing rocks... tragedy is inevitable" and labels them "violent, anti-American radicals." This content's usefulness is supported by my knowledge that [[Nixon actively appealed to the 'Silent Majority' of patriotic, law-abiding Americans who resented radical student protesters, using a law-and-order stance to justify the war and police actions]], which confirms that the speech is typical of Nixon's political strategy. {{The provenance of a televised presidential speech in May 1970 is highly useful because it shows how the government officially sought to manage the crisis and turn public opinion against the student demonstrators. However, it is less useful because it is a political speech designed to deflect blame from the National Guard and maintain support for Nixon's Cambodia policy.}}`,

  mock_exam_3:
`Source B is highly useful for showing the official, legalistic methods of resistance deployed by Southern politicians to defy integration. The photograph depicts "a group of Southern Senators and Congressmen signing the Southern Manifesto", pledging to use all lawful means to resist federal rulings. This content is highly useful because it is supported by my contextual knowledge that [[in March 1956, over 100 Southern politicians signed the Southern Manifesto to coordinate resistance, falsely claiming the Supreme Court's Brown ruling was an abuse of judicial power]], which confirms that the photograph is an accurate representation of how Southern elites lent political legitimacy to segregation. {{The provenance makes the source highly useful because it documents a historic moment of political mobilization in March 1956, showing the unity of Southern lawmakers. However, it is limited because it only captures a public signing ceremony, concealing the illegal, violent tactics and economic intimidation that these same state authorities quietly condoned on the ground.}}\n\nSource E is highly useful for showing the violent and physical intimidation used by extremist groups to enforce segregation. The photograph depicts "dozens of Klansmen in white robes and pointed hoods marching" down a street while police stand by. This content's utility is supported by my knowledge that [[the Ku Klux Klan experienced a major revival in the 1950s, using bombings, beatings, and lynchings to terrorize civil rights workers with local police collusion]], which confirms the accuracy of the source as a record of KKK activity. {{The provenance, showing a KKK march in 1957, makes the source highly useful because it shows the public, unchecked presence of white supremacist groups. However, it is less useful because it only captures a public parade, failing to document the illegal, clandestine nature of KKK violence and their collusion with local police.}}`,

  mock_exam_4:
`Source B is highly useful for showing the student perspective and moral outrage surrounding the Kent State shootings. The student describes the rally as a "peaceful rally against the President's illegal invasion of Cambodia" and accuses the National Guard of firing "live ammunition directly into the crowd of unarmed students." This content is highly useful because it is supported by my contextual knowledge that [[the Kent State shootings in May 1970, where National Guardsmen fired 67 rounds into a crowd, killing four and wounding nine students, became a symbol of extreme government suppression]], which confirms that the eyewitness account captures the authentic feeling of shock and alienation. {{The provenance of a student magazine published in May 1970 increases its usefulness because it provides an immediate, unedited record of student anger. However, it is limited because it represents a highly partisan student viewpoint that ignores the pre-existing tensions, arson of the ROTC building, and rock-throwing that preceded the guard's reaction.}}\n\nSource C is highly useful for understanding the Nixon administration's perspective and their framing of anti-war protesters to maintain conservative support. Nixon asserts that "when students resort to throwing rocks... tragedy is inevitable" and labels them "violent, anti-American radicals." This content's usefulness is supported by my knowledge that [[Nixon actively appealed to the 'Silent Majority' of patriotic, law-abiding Americans who resented radical student protesters, using a law-and-order stance to justify the war and police actions]], which confirms that the speech is typical of Nixon's political strategy. {{The provenance of a televised presidential speech in May 1970 is highly useful because it shows how the government officially sought to manage the crisis and turn public opinion against the student demonstrators. However, it is less useful because it is a political speech designed to deflect blame from the National Guard and maintain support for Nixon's Cambodia policy.}}`,

  mock_exam_5:
`Source B is highly useful for understanding the military strategy and resilience of the communist forces. The commander explains that they "used the jungle and our tunnels to neutralise their air power" and aimed to "keep fighting until the American public grew tired of the war". This content is highly useful because it is supported by my contextual knowledge that [[the communists waged a war of attrition, utilizing the Cu Chi tunnels and jungle cover to survive US bombing, counting on growing anti-war sentiment in the US to force a withdrawal]], which confirms that the commander's statement is an accurate reflection of their military strategy. {{The provenance of a post-war interview with a North Vietnamese commander in 1982 makes it useful because it offers an official retrospective explanation of their victory. While he has a natural interest in emphasizing their ideological determination and heroic sacrifice, it is highly useful for showing the strategic patience that allowed them to defeat a technologically superior superpower.}}\n\nSource C is highly useful for showing how US military tactics alienated the civilian population in South Vietnam. The report states that heavy reliance on "search-and-destroy operations and chemical defoliants has created hundreds of thousands of refugees" and is driving peasants "directly into the arms of the enemy". This content's utility is supported by my knowledge that [[tactics like search-and-destroy and the chemical spraying of Agent Orange under Operation Ranch Hand alienated the rural population, making it impossible to win the hearts and minds campaign]], which explains why US tactics actively fueled the communist insurgency. {{The provenance strengthens its usefulness because it is an official report by a US Senate Subcommittee in 1968. Since it is a self-critical government investigation, it provides a highly reliable, objective contemporary record of the counterproductive nature of US military operations.}}`,

  mock_exam_6:
`Source B is highly useful for showing the SCLC's strategic methods of non-violent mobilization and church-based organization. The author reports that King spoke to "several thousand people" in a church, asking them to "remain non-violent" and to ride the buses again under a new spirit of dignity. This content is highly useful because it is supported by my contextual knowledge that [[the Montgomery Improvement Association, led by MLK, organized regular mass meetings in Black churches to sustain community morale and enforce non-violent discipline during the 381-day bus boycott]], which confirms that the newsletter provides an accurate representation of the movement's religious foundation. {{The provenance increases the source's utility because it is an internal newsletter published in early 1956. While it was intended as a motivational piece that downplays internal divisions or exhaustion, it is highly useful for showing the official rhetoric used to keep the community united during a prolonged crisis.}}\n\nSource C is highly useful for demonstrating the legal opposition and hostile reactions of local white authorities to the boycott. Mayor Gayle declares that the boycott is "an illegal economic conspiracy" and that they have "no intention of negotiating with lawbreakers." This content's usefulness is supported by my knowledge that [[Montgomery city officials used local laws to indict MLK and 80 other boycott leaders for disrupting lawful business, attempting to crush the protest through legal intimidation]], which confirms that the Mayor's public resistance was typical of Southern political elites. {{The provenance of a statement by the Montgomery Mayor in January 1956 makes the source extremely useful because it captures the official segregationist position at the height of the boycott, showing their determination to defend the Jim Crow system. However, it is less useful because it frames the dispute purely as a legal matter, hiding the extra-legal violence and KKK intimidation that authorities tolerated on the ground.}}`,

  mock_exam_7:
`Source B is highly useful for showing the psychological strain and tactical difficulties faced by US ground forces in Vietnam. The soldier writes about patrolling in circles through a swamp where they "cannot see the enemy, but we know they are there" and are losing men to mines, noting that they are "fighting a shadow, and we are losing our minds". This content's utility is supported by my knowledge that [[the Vietcong used guerrilla warfare, tunnels, and booby traps in the Mekong Delta, which neutralised US conventional firepower and caused severe psychological stress for soldiers]], which explains the intense exhaustion and fear expressed in his diary. {{The provenance, a personal diary entry from 1967, makes the source extremely useful. Because it was written privately for himself and not for military censors or the public, it represents a highly reliable, authentic record of the daily physical and psychological toll of guerrilla warfare.}}\n\nSource C is highly useful for understanding the military strategy and resilience of the communist forces. The commander explains that they "used the jungle and our tunnels to neutralise their air power" and aimed to "keep fighting until the American public grew tired of the war". This content is highly useful because it is supported by my contextual knowledge that [[the communists waged a war of attrition, utilizing the Cu Chi tunnels and jungle cover to survive US bombing, counting on growing anti-war sentiment in the US to force a withdrawal]], which confirms the accuracy of the commander's strategic recollections. {{The provenance of a post-war interview with a North Vietnamese commander in 1982 makes it useful because it offers an official retrospective explanation of their victory. While he has a interest in emphasizing their ideological determination and heroic sacrifice, it is highly useful for showing the strategic patience that allowed them to defeat a technologically superior superpower.}}`
};

// ==========================================
// 3. EXECUTION OF REWRITES
// ==========================================

console.log('Starting rewrites in src/lessons_data.js...');
let lessonsText = fs.readFileSync('./src/lessons_data.js', 'utf8');

for (const [subtopicId, newAnswer] of Object.entries(LESSON_ANSWERS)) {
  try {
    lessonsText = replaceModelAnswer(lessonsText, subtopicId, newAnswer);
    console.log(`- Successfully updated subtopic: ${subtopicId}`);
  } catch (err) {
    console.error(`- Error updating ${subtopicId}:`, err.message);
  }
}

fs.writeFileSync('./src/lessons_data.js', lessonsText, 'utf8');
console.log('Saved src/lessons_data.js.');

console.log('\nStarting rewrites in questions.js...');
let questionsText = fs.readFileSync('./questions.js', 'utf8');

for (const [questionId, newAnswer] of Object.entries(EXAM_ANSWERS)) {
  try {
    questionsText = replaceExamsModelAnswer(questionsText, questionId, newAnswer);
    console.log(`- Successfully updated question: ${questionId}`);
  } catch (err) {
    console.error(`- Error updating ${questionId}:`, err.message);
  }
}

fs.writeFileSync('./questions.js', questionsText, 'utf8');
console.log('Saved questions.js.');
