const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '../src/lessons_data.js');

// 1. Load the data using a temp CommonJS file to bypass ES modules restrictions in Node
const fileContent = fs.readFileSync(filePath, 'utf8');
let cleanContent = fileContent.replace('export const LESSONS_DATA =', 'const data =') + '; module.exports = data;';
fs.writeFileSync(path.join(__dirname, 'temp_lessons_data.js'), cleanContent);
const LESSONS_DATA = require('./temp_lessons_data.js');
fs.unlinkSync(path.join(__dirname, 'temp_lessons_data.js'));

// 2. Define the new model answers
const NEW_MODEL_ANSWERS = {
  "subtopic_1_1": `Source D is highly useful for showing the response of activists and the direct police criminalization of peaceful protestors in the South. For example, the photograph depicts "Rosa Parks standing calm and dignified" while being fingerprinted by a police officer in uniform. This is supported by my contextual knowledge that [[Rosa Parks' refusal to give up her seat in December 1955 sparked the Montgomery Bus Boycott, which lasted 381 days and successfully desegregated buses]]. The provenance strengthens the source's utility because it was taken on 22 February 1956, during the height of the boycott, making it a reliable, contemporary visual record of the state's attempt to intimidate boycott leaders. However, its usefulness is slightly limited because it is a staged publicity photo that only captures a single moment of arrest, failing to show the NAACP's broader legal strategy.

Source E is highly useful for demonstrating the systemic, official nature of segregation in public facilities in the 1950s. The photograph shows a wooden sign reading "COLORED WAITING ROOM" hanging above a public entrance. This is supported by my knowledge that [[Jim Crow laws in the Southern states officially enforced segregation in transit, restaurants, and schools, creating separate and unequal conditions]]. The provenance, taken in the Southern United States in the early 1950s, makes the source extremely useful because it provides direct, unedited evidence of state-sanctioned racial infrastructure. However, it is less useful because it only shows the sign itself, failing to document the personal experiences of the Black passengers who suffered under segregation or the active resistance against it.`,

  "subtopic_1_2": `Source D is highly useful for showing the intense social opposition and grassroots white resistance to school integration. The photograph depicts an "angry white crowd" of students and adults protesting, with some carrying signs reading "Keep Central High Clean". This aligns with my contextual knowledge that [[when the Little Rock Nine attempted to integrate Central High School in September 1957, they faced violent, threatening white mobs who surrounded the school]]. The provenance, taken outside Central High in September 1957, makes the source highly useful because it captures the raw, authentic hostility of the segregationists at the exact moment of the crisis. However, it is less useful because it only represents the vocal extremist protesters, failing to show the moderate white citizens or the experiences of the Black students inside the school.

Source E is highly useful for showing the scale of the state and military conflict required to override this local segregationist opposition. The photograph shows "armed federal troops standing in single file" holding bayonets. This is supported by my knowledge that [[Governor Orval Faubus used the National Guard to block the Black students, forcing President Eisenhower to send 1,000 soldiers of the 101st Airborne Division to enforce integration]]. The provenance of late September 1957 makes the source extremely useful because it documents the historic federal intervention needed to uphold the Constitution. However, it is slightly less useful because it portrays a staged, orderly military patrol, which hides the constant, daily psychological harassment the students endured from white classmates inside the classrooms.`,

  "subtopic_1_3": `Source D is highly useful for showing the spiritual leadership and religious solidarity that sustained the boycott. The photograph shows Martin Luther King Jr. "speaking passionately from a pulpit" to a church "completely packed with Black citizens". This is supported by my knowledge that [[the Montgomery Improvement Association (MIA) held regular mass meetings in local churches to coordinate strategy, maintain non-violent discipline, and raise funds for the boycott]]. The provenance of late 1955 makes the source highly useful because it captures the central role of the Black church as the organizational hub at the very beginning of the boycott. However, it is less useful because it focuses solely on Dr. King's charismatic leadership, omitting the crucial organizing work of figures like Jo Ann Robinson and the Women's Political Council.

Source E is highly useful for showing the high level of logistical planning and coordination behind the boycott. The photograph depicts "several private station wagons lined up" while an organizer with a clipboard coordinates destinations. This is supported by my knowledge that [[the MIA organized an extensive carpool network of over 300 private cars and 40 pickup stations to transport 15,000 Black citizens daily without using the city buses]]. The provenance of early 1956 makes the source extremely useful because it provides contemporary visual proof of the sophisticated logistics that allowed the boycott to survive for 381 days. However, it is less useful because it presents an orderly, peaceful scene, failing to show the bomb threats, legal harassment, and police intimidation that carpool drivers faced.`,

  "subtopic_1_4": `Source D is highly useful for showing the organized and public methods used by 'respectable' segregationists to resist civil rights. The photograph shows a highway billboard reading "Help segregation! Support the White Citizens Council". This aligns with my knowledge that [[White Citizens' Councils, formed across the South in the mid-1950s, used economic pressure—such as firing Black activists and foreclosing mortgages—to quietly crush the integration movement]]. The provenance of 1956 in Alabama makes the source highly useful because it demonstrates how segregationist groups openly marketed their resistance to the public. However, it is less useful because it only displays public propaganda, hiding the quiet, devastating economic terrorism these councils inflicted behind closed doors.

Source E is highly useful for showing the violent and physical intimidation used by extremist groups to enforce segregation. The photograph depicts "dozens of Klansmen in white robes and pointed hoods marching" down a street while police stand by. This is supported by my knowledge that [[the Ku Klux Klan experienced a major revival in the 1950s, using bombings, beatings, and lynchings to terrorize civil rights workers with local police collusion]]. The provenance, showing a KKK march in 1957, makes the source highly useful because it shows the public, unchecked presence of white supremacist groups. However, it is less useful because it only captures a public parade, failing to document the illegal, clandestine nature of KKK violence and their collusion with local police.`,

  "subtopic_2_1": `Source D is highly useful for showing the non-violent direct action tactics used by student activists to challenge retail segregation. The photograph shows "four Black college students sitting quietly" on counter stools while white teenagers pour sugar on them. This aligns with my knowledge that [[the Greensboro sit-in of February 1960 at Woolworth's sparked a massive sit-in movement across the South, demonstrating SNCC's commitment to non-violent resistance]]. The provenance, taken in February 1960, makes the source highly useful because it provides an authentic, contemporary record of the physical harassment activists endured to expose Southern bigotry. However, it is less useful because it only shows the counter itself, omitting the wider economic boycott of the store organized by the local community that forced integration.

Source E is highly useful for showing the extreme level of state resistance to university integration and the federal intervention needed to override it. The photograph depicts James Meredith walking "flanked by several tall, serious US Marshals" wearing helmets. This is supported by my knowledge that [[Governor Ross Barnett defied federal orders, prompting President Kennedy to send 30,000 troops and US Marshals to force the integration of the University of Mississippi in October 1962, sparking riots that killed two people]]. The provenance of October 1962 makes the source extremely useful because it visually documents the armed federal power needed to protect Black rights. However, it is less useful because it depicts a controlled walk, failing to capture the chaos and violence of the Ole Miss riot itself.`,

  "subtopic_2_2": `Source D is highly useful for showing the massive scale, unity, and public impact of non-violent civil rights campaigns. The photograph depicts Martin Luther King Jr. "looking out over a massive crowd of over 250,000 demonstrators" surrounding the reflecting pool. This is supported by my knowledge that [[the March on Washington in August 1963 was a key moment of multi-racial unity that put pressure on the Kennedy administration to pass civil rights laws]]. The provenance of 28 August 1963 makes the source highly useful because it captures the peak of the movement's public mobilization. However, it is less useful because it highlights a single speech, obscuring the deep strategic disagreements between SNCC, SCLC, and other coalition members behind the scenes.

Source E is highly useful for showing the political and legislative outcomes of grassroots non-violent campaigns. The photograph shows President Johnson "handing a commemorative pen to Martin Luther King Jr." and other leaders at the desk. This is supported by my knowledge that [[the legislative alliance between LBJ and civil rights leaders led to the passage of the Voting Rights Act of 1965, which banned literacy tests and authorized federal registrars]]. The provenance of 6 August 1965 makes the source extremely useful because it documents the formal signing of this landmark act. However, it is less useful because it portrays a harmonious political consensus, hiding the intense pressure, political caution, and FBI surveillance that Johnson's administration directed at civil rights leaders.`,

  "subtopic_2_3": `Source D is highly useful for understanding the intellectual shift toward self-defense and militancy. The photograph shows Malcolm X pointing to a newspaper headline that reads "Blacks Must Defend Themselves Against Klan Terror!". This aligns with my knowledge that [[Malcolm X rejected SCLC's non-violent integration, advocating Black nationalism, economic self-reliance, and self-defense 'by any means necessary' to appeal to Northern urban Black communities]]. The provenance of 1964 makes the source highly useful because it documents how Malcolm X used print media to directly challenge MLK's non-violent orthodoxy. However, it is less useful because it is a posed, strategic media photograph designed to project militancy, rather than showing Malcolm's complex intellectual evolution.

Source E is highly useful for showing how Black Power and militancy were institutionalized by student groups in the late 1960s. The photograph depicts a "column of Black Panther members wearing black leather jackets, black berets" marching in formation. This is supported by my knowledge that [[the Black Panther Party, founded in 1966 in Oakland, California, rejected integration and police brutality, calling for armed patrols and community self-reliance]]. The provenance of 1968 makes the source extremely useful because it visually captures the disciplined, militaristic style of Black Power. However, it is less useful because it focuses on their armed, militant appearance, ignoring their extensive community welfare programs, such as free breakfasts for children.`,

  "subtopic_2_4": `Source D is highly useful for showing the scale of violence, property destruction, and military deployment during the urban riots. The photograph shows "armed National Guardsmen standing in front of burning storefronts" in Detroit. This is supported by my knowledge that [[the Detroit Riot of July 1967 resulted in 43 deaths, over 1,000 injuries, and prompted the Kerner Commission to investigate the systemic racism and poverty in Northern ghettos]]. The provenance of July 1967 makes the source highly useful because it provides an authentic, contemporary record of the military force needed to suppress urban rebellions. However, it is less useful because it focuses on the law-and-order response, failing to depict the underlying causes of the riot, such as police brutality and housing discrimination.

Source E is highly useful for showing the immediate political and emotional impact of MLK's death on Black Americans. The photograph shows a "large crowd... carrying signs that read 'Honor King: End Racism Now'" with smoldering buildings in the background. This is supported by my knowledge that [[the assassination of Martin Luther King Jr. on 4 April 1968 sparked violent riots in over 100 cities, marking the end of the non-violent civil rights era]]. The provenance of April 1968 in Washington D.C. makes the source extremely useful because it captures the national grief and outrage. However, it is less useful because it portrays a peaceful march, failing to represent the violent riots and arson that occurred in Washington D.C. at the same time.`,

  "subtopic_3_1": `Source D is highly useful for showing President Diem's authoritarian methods and his reliance on military forces to maintain power. The photograph shows "Diem standing in an open-top car, reviewing rows of South Vietnamese soldiers" carrying US-supplied weapons. This is supported by my knowledge that [[the US supported Diem's anti-communist regime with massive military aid and advisors from 1955, despite his corruption, nepotism, and lack of peasant support]]. The provenance of October 1957 makes the source highly useful because it illustrates how the regime projected military authority to hide its internal weaknesses. However, it is less useful because it shows a highly staged state event in Saigon, concealing the lack of peasant support and the growing communist insurgency in the countryside.

Source E is highly useful for showing the scale of religious opposition that undermined Diem's regime. The photograph shows a "massive crowd of Buddhist monks and nuns sitting in a street, holding banners reading 'Stop Religious Persecution!'". This aligns with my knowledge that [[Diem's favoritism toward the Catholic minority and suppression of the Buddhist majority sparked the Buddhist Crisis of 1963, including self-immolations that destroyed the regime's international legitimacy]]. The provenance of June 1963 makes the source extremely useful because it captures the public crisis that forced the US to support a military coup against Diem in November 1963. However, it is less useful because it only captures the peaceful protests, omitting the violent police raids on pagodas.`,

  "subtopic_3_2": `Source D is highly useful for showing the US naval presence that served as the trigger for direct combat escalation. The photograph shows the "USS Maddox traveling through calm seas" with gun turrets aimed toward the horizon. This aligns with my knowledge that [[the Gulf of Tonkin incidents of August 1964 led Congress to pass the Gulf of Tonkin Resolution, giving President Johnson a 'blank check' to escalate US military involvement]]. The provenance of August 1964 makes the source highly useful because it documents the actual vessel involved in the clashes. However, it is less useful because it shows a calm, routine patrol, failing to clarify the disputed and confusing details of the attacks.

Source E is highly useful for showing the transition to full combat operations and the deployment of ground troops. The photograph shows "US Marines carrying heavy backpacks and rifles wading through shallow water" onto Da Nang beach. This is supported by my knowledge that [[the landing of the 9th Marine Expeditionary Brigade in March 1965 marked the official start of the US ground war, with troop levels rising to 184,000 by the end of 1965]]. The provenance of 8 March 1965 makes the source extremely useful because it captures the historical moment of transition to direct combat. However, it is less useful because the presence of local women handing out flowers was a staged public relations event, hiding the hostile, muddy reality of combat that the Marines would soon face.`,

  "subtopic_3_3": `Source D is highly useful for showing the tactical and physical challenges that US combat patrols faced. The photograph shows a US soldier "wading waist-deep through muddy swamp water in dense jungle" holding his rifle high. This aligns with my knowledge that [[US Search and Destroy tactics designed to find the Vietcong faced terrain problems and ambush vulnerability, as the Vietcong used booby traps and the jungle environment to neutralize US technology]]. The provenance of 1967 makes the source highly useful because it offers a realistic, gritty look at the brutal environmental conditions. However, it is less useful because it focuses on a single soldier's exhaustion, failing to show the high civilian casualties and destruction of villages that search-and-destroy missions often caused.

Source E is highly useful for showing the chemical warfare tactics used by the US to counter these environmental challenges. The photograph shows "C-123 military transport planes... releasing thick white chemical trails of Agent Orange" over dense forest. This is supported by my knowledge that [[Operation Ranch Hand sprayed millions of gallons of herbicides to strip jungle cover and destroy crops, which poisoned food supplies and alienated the peasant population]]. The provenance of 1966 makes the source extremely useful because it documents the systematic, industrial scale of chemical defoliation. However, it is less useful because it presents a clean, aerial view of the spraying, omitting the devastating health consequences, birth defects, and political backlash among Vietnamese peasants.`,

  "subtopic_3_4": `Source D is highly useful for showing the public relations campaign used to justify Vietnamization. The photograph shows "Nixon standing in a crowd of smiling US soldiers" in combat uniforms. This aligns with my knowledge that [[President Nixon introduced 'Vietnamization' in 1969 to gradually withdraw US combat troops while shifting responsibility to the ARVN, seeking 'peace with honor' to satisfy the public]]. The provenance of July 1969 makes the source highly useful because it illustrates the presidential photo opportunity used to project troop support. However, it is less useful because it is a carefully managed event, masking the low morale, drug use, and growing anti-war sentiment among the soldiers in the field.

Source E is highly useful for showing that Vietnamization actually expanded the geographical scope of the war. The photograph shows "ARVN soldiers running past a burning tank on a dirt road in Cambodia" with helicopters overhead. This is supported by my knowledge that [[Nixon ordered the invasion of Cambodia in May 1970 to destroy communist sanctuaries and supply lines, which failed to secure South Vietnam and sparked massive protests at Kent State]]. The provenance of May 1970 makes the source extremely useful because it shows ARVN troops in active combat. However, it is less useful because it portrays a successful tactical advance, failing to show the strategic failure of the campaign or the ARVN's heavy reliance on US air power.`,

  "subtopic_4_1": `Source D is highly useful for showing the youth-led, confrontational nature of the anti-war movement. The photograph shows "young demonstrators carrying peace signs... facing a wall of military police". This aligns with my knowledge that [[the Pentagon protest of October 1967 reflected the rapid growth of the anti-war movement as the draft escalated, with draft card burning and peaceful marches becoming common]]. The provenance of October 1967 makes the source highly useful because it captures the direct, non-violent confrontation with military authority. However, it is less useful because it focuses on a single demonstration in Washington D.C., failing to show the wider, working-class opposition or moderate critics of the war.

Source E is highly useful for showing the lethal escalation of state suppression of student protests on campus. The photograph shows a "line of National Guard soldiers... aimed toward them, holding rifles" at Kent State. This is supported by my knowledge that [[the Kent State shootings of May 1970, where National Guardsmen killed four students protesting the invasion of Cambodia, triggered a strike of 4 million students nationwide]]. The provenance of May 1970 makes the source extremely useful because it documents the tense standoff just before the shooting. However, it is less useful because it captures the standoff, failing to explain the panic, chaos, and nationwide student strike that followed.`,

  "subtopic_4_2": `Source D is highly useful for showing the organized public support for President Nixon's policies. The photograph shows citizens holding signs reading "Support Our President" and "Silent Majority Speaks". This aligns with my knowledge that [[President Nixon's November 1969 speech appealed to the 'Silent Majority'—the patriotic, law-abiding middle-class citizens who did not join protests—to politically counter the anti-war movement]]. The provenance of 1970 makes the source highly useful because it proves that pro-war citizens actively adopted Nixon's rhetoric. However, it is less useful because it is a pro-war rally, which may exaggerate the active support of the average citizen who was simply silent or disengaged.

Source E is highly useful for showing the working-class basis of this pro-war support and the polarization of the home front. The photograph shows "construction workers... marching... banners reading 'USA All the Way'". This is supported by my knowledge that [[the Hard Hat Riots of May 1970, where construction workers attacked students protesting the Kent State shootings in New York City, revealed deep class divisions on the home front]]. The provenance of May 1970 makes the source extremely useful because it documents the intense, working-class backlash against student protestors. However, it is less useful because it shows workers marching, concealing the complex economic anxieties and union politics that also drove their opposition to student demonstrators.`,

  "subtopic_4_3": `Source D is highly useful for showing the formal, diplomatic conclusion of US military involvement in Vietnam. The photograph shows "diplomats sitting around a massive circular table... signing the official treaty" in Paris. This aligns with my knowledge that [[the signing of the Paris Peace Accords in January 1973 ended direct US military involvement, securing the withdrawal of US troops and the return of POWs]]. The provenance of 27 January 1973 makes the source highly useful because it documents the formal legal conclusion of the war. However, it is less useful because it portrays a polished, peaceful diplomatic consensus, ignoring the secret negotiations, pressure on South Vietnamese President Thieu, and the fact that fighting continued between North and South.

Source E is highly useful for showing the chaotic, real-world failure of the peace treaty and the collapse of Vietnamization. The photograph shows a "long line of people climbing a ladder onto the roof... to board a CIA Huey helicopter" at the US embassy. This is supported by my knowledge that [[the Fall of Saigon in April 1975, when North Vietnamese forces captured the capital and South Vietnam surrendered, marked the final failure of US containment policy in Indochina]]. The provenance of 29 April 1975 makes the source extremely useful because it provides a raw, iconic visual record of defeat. However, it is less useful because it focuses on the panic at the evacuation point, failing to capture the military campaigns and political decisions that led to the final collapse.`,

  "subtopic_4_4": `Source D is highly useful for showing the tactical and military challenges that caused US failure. The photograph shows several soldiers "wading through thick mud and reeds in a swamp" in Vietnam. This aligns with my knowledge that [[US conventional advantages in heavy armor and firepower were neutralized by the difficult swamp and jungle terrain, which favored Vietcong guerrilla warfare and ambush tactics]]. The provenance of 1968 makes the source highly useful because it visually represents the physical and tactical quagmire that US combat patrols faced. However, it is less useful because it only shows the tactical environment, failing to represent the strategic failures of the search-and-destroy policy or the political instability in Saigon.

Source E is highly useful for showing the political and moral collapse of the war effort at home. The photograph shows "veterans... throwing their military medals and ribbons over a wire fence" in front of the Capitol. This is supported by my knowledge that [[the Vietnam Veterans Against the War (VVAW) protests of 1971, which included veterans testifying about war crimes, severely damaged the government's moral credibility]]. The provenance of 1971 in Washington D.C. makes the source extremely useful because it shows the deep moral and political disillusionment of the soldiers who fought. However, it is less useful because it represents the views of highly politicized, activist veterans, rather than the silent majority of returning soldiers who did not join protests.`
};

// 3. Update the LESSONS_DATA object
for (const [subtopicId, newModel] of Object.entries(NEW_MODEL_ANSWERS)) {
  if (LESSONS_DATA[subtopicId] && LESSONS_DATA[subtopicId].howUsefulAnalyser) {
    LESSONS_DATA[subtopicId].howUsefulAnalyser.modelAnswer = newModel;
    console.log(`✓ Updated modelAnswer in LESSONS_DATA for ${subtopicId}`);
  } else {
    console.error(`❌ Could not find subtopic ${subtopicId} or howUsefulAnalyser inside it.`);
  }
}

// 4. Write back to src/lessons_data.js
const newContent = 'export const LESSONS_DATA = ' + JSON.stringify(LESSONS_DATA, null, 2) + ';\n';
fs.writeFileSync(filePath, newContent, 'utf8');
console.log('✓ Successfully wrote lessons_data.js back!');
